# 暂时还无法做到完全自动化
# 还需要和后端对接文件上传地址

image: zzzzzzshpig/qm-ci-app

stages:
  - install_package
  - build_dev
  - build_prod
  - deploy_dev
  - deploy_prod

variables:
  PROXY: http://192.168.1.77:8123
  DEV_CDN_PATH: /new_xiangju_ts_dev/dist/ # 测试 cdn 地址
  PROD_CDN_PATH: /new_xiangju_ts/dist/ # 线上 cdn 地址
  DEV_INDEX_PATH: /xiangju_new_admin_ts_dev/dist/ # 测试 index.html 上传地址
  PROD_INDEX_PATH: /new_admin_ts/dist/ # 线上 index.html 上传地址

before_script:
  - pwd

.is_dev: &is_dev
  only:
    - /^dev\//
  except:
    - branches

.is_release: &is_release
  only:
    - /^release\//
  except:
    - branches

# build的公共步骤
.build_merge: &build_merge
  artifacts:
    paths:
      - dist/
    expire_in: 12 hours
  # 拉取node_modules缓存
  cache:
    paths:
      - node_modules/
    policy: pull

# yarn install
install_package:
  stage: install_package
  script:
    - node -v
    - yarn -v
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.malmam.com".insteadOf "https://gitlab.malmam.com"
    - yarn install
  cache: # 缓存 node_modules
    paths:
      - node_modules
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(dev|release)\//

# 测试build
build_dev:
  stage: build_dev
  script:
    - yarn dev_build
  <<: *build_merge
  <<: *is_dev

# 线上build
build_prod:
  stage: build_prod
  script:
    - yarn build
  <<: *build_merge
  <<: *is_release

# 上传文件前的公共步骤
.deploy_before_script: &deploy_before_script
  - cp -f deploy/.cos.conf ~/
  - mkdir -p ~/.ssh || true
  - cp -f deploy/id_rsa ~/.ssh/
  - chmod 600 ~/.ssh/id_rsa

# 测试发布
deploy_dev:
  stage: deploy_dev
  before_script:
    - *deploy_before_script
  script:
    # 将dist目录传到 Tencent cdn 指定位置
    - coscmd upload -rs ./dist/ $DEV_CDN_PATH
    # 将index.html 传到指定位置
    - ssh -p 6622 -o "StrictHostKeyChecking no" nukq@192.168.1.66 "mkdir -p "/home/nukq/www${DEV_INDEX_PATH}" >>/dev/null"
    - rsync -ave "ssh -p 6622 -o \"StrictHostKeyChecking no\""  --safe-links --checksum --omit-dir-times ./dist/index.html nukq@192.168.1.66:"/home/nukq/www${DEV_INDEX_PATH}/"
  <<: *is_dev

# 线上发布
deploy_prod:
  stage: deploy_prod
  before_script:
    - *deploy_before_script
  script:
    # 将dist目录传到 Tencent cdn 指定位置
    - coscmd upload -rs ./dist/ $PROD_CDN_PATH
    # 将index.html 传到指定位置
    - ssh -p 65535 -o "StrictHostKeyChecking no" nukq@www1.mipang.com "mkdir -p "/data/www/xiangju/public${PROD_INDEX_PATH}" >>/dev/null"
    - ssh -p 65535 -o "StrictHostKeyChecking no" nukq@www2.mipang.com "mkdir -p "/data/www/xiangju/public${PROD_INDEX_PATH}" >>/dev/null"
    - ssh -p 65524 -o "StrictHostKeyChecking no" nukq@www1.mipang.com "mkdir -p "/data/www/xiangju/public${PROD_INDEX_PATH}" >>/dev/null"
    - rsync -ave "ssh -p 65535 -o \"StrictHostKeyChecking no\""  --safe-links --checksum --omit-dir-times ./dist/index.html nukq@www1.mipang.com:"/data/www/xiangju/public${PROD_INDEX_PATH}/"
    - rsync -ave "ssh -p 65535 -o \"StrictHostKeyChecking no\""  --safe-links --checksum --omit-dir-times ./dist/index.html nukq@www2.mipang.com:"/data/www/xiangju/public${PROD_INDEX_PATH}/"
    - rsync -ave "ssh -p 65524 -o \"StrictHostKeyChecking no\""  --safe-links --checksum --omit-dir-times ./dist/index.html nukq@www1.mipang.com:"/data/www/xiangju/public${PROD_INDEX_PATH}/"
  <<: *is_release
